backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "cursos"
    label: "Cursos"
    folder: "data/cursos"  # Cambia 'file' por 'folder'
    create: true
    slug: "{{slug}}"      # Genera nombres de archivo automáticos
    fields:
      - { name: "titulo", label: "Título", widget: "string" }
      - { name: "descripcion", label: "Descripción", widget: "text" }
      - { name: "imagen", label: "Imagen", widget: "image" }
      - { name: "duracion", label: "Duración", widget: "string" }
      - { name: "activo", label: "¿Activo?", widget: "boolean", default: true }